pub const HOMA_SOCKET_PATH: &str = "/tmp/homa.sock";
pub const HOMA_DATAGRAM_PAYLOAD_LENGTH: u16 = 128;
pub const HOMA_MESSAGE_MAX_LENGTH: u64 = 524_288_000;
pub const MESSAGE_RECEIVER_TIMEOUT: u64 = 500;
pub const MESSAGE_SENDER_TIMEOUT: u64 = 500;
pub const UNSCHEDULED_HOMA_DATAGRAM_LIMIT: usize = 5;
